// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLkzI-mUKDhT35a-qP9zA3Zfh4q38o5Ac',
    appId: '1:303627114664:android:5acea060968d5cad6d8a9d',
    messagingSenderId: '303627114664',
    projectId: 'whatsapp-backend-edeaf',
    storageBucket: 'whatsapp-backend-edeaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS0fsar2AwtmlnWbMYnTQx6u1jeNhxE7Q',
    appId: '1:303627114664:ios:0d69664f04065c146d8a9d',
    messagingSenderId: '303627114664',
    projectId: 'whatsapp-backend-edeaf',
    storageBucket: 'whatsapp-backend-edeaf.appspot.com',
    iosClientId: '303627114664-2ru7v48ialgj8so7s7mhjbh9gmc2n0ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappWithBackend',
  );
}
